# *****************************************************************
# * File:        makefile                                         *
# * Author:      Alejandro Palacio Caro                           *
# * Instructor:  Dr. David A. Gaitros                             *
# * Course:      COP3330 - Data Structures and Algorithm Analysis I *
# * Assignment:  Project #4 – Sudoku Puzzle Analyzer              *
# * Date:        June 27, 2025                                    *
# * Description: Compilation instructions for sudoku.cpp and      *
# *              main.cpp using g++ and C++11 standard. Produces  *
# *              an executable named 'main' for linprog testing.  *

# *****************************************************************
# * File:        makefile                                         *
# * Author:      Alejandro Palacio Caro                           *
# * Instructor:  Dr. David A. Gaitros                             *
# * Course:      COP3330 - Data Structures and Algorithm Analysis I *
# * Assignment:  Project #4 – Sudoku Puzzle Analyzer              *
# * Date:        June 27, 2025                                    *
# * Description: Compilation instructions for sudoku.cpp and      *
# *              main.cpp using g++ and C++11 standard. Produces  *
# *              an executable named 'main' for linprog testing.  *
# *****************************************************************

main: main.cpp sudoku.cpp
        g++ -std=c++11 -o main main.cpp sudoku.cpp

main: main.cpp sudoku.cpp
	g++ -std=c++11 -o main main.cpp sudoku.cpp
